# Generated by Django 4.0.3 on 2022-03-07 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_tags_tag_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
    ]
