# Generated by Django 4.0.3 on 2022-03-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_tag_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
