# Generated by Django 4.0.3 on 2022-03-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_tag_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='status',
        ),
        migrations.AddField(
            model_name='articletag',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
