# Generated by Django 4.0.3 on 2022-03-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_tag_status_articletag_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(through='articles.ArticleTag', to='articles.article'),
        ),
    ]
