# Generated by Django 4.0.3 on 2022-03-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_tag_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
