# Generated by Django 4.0.3 on 2022-03-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_remove_tag_article_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='scopes', through='articles.ArticleTag', to='articles.tag'),
        ),
    ]
