# Generated by Django 4.0.3 on 2022-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='status',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
