# Generated by Django 4.0.3 on 2022-03-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_tag_is_main_articletag_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletag',
            name='is_main',
        ),
        migrations.AddField(
            model_name='tag',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
    ]
